export const release = {
  name: "Nova 2.4 Launch",
  date: "July 21, 2026",
  today: "July 18, 2026",
  days: [
    { id: "jul-14", weekday: "Tue", date: "14" },
    { id: "jul-15", weekday: "Wed", date: "15" },
    { id: "jul-16", weekday: "Thu", date: "16" },
    { id: "jul-17", weekday: "Fri", date: "17" },
    { id: "jul-18", weekday: "Sat", date: "18", today: true },
  ],
};

export const lanes = [
  {
    id: "claim",
    label: "Claim",
    description: "What we promise",
    events: [
      {
        id: "claim-14",
        status: "verified",
        title: "Privacy promise v1.0 published",
        revision: "rev 1a7c3d2",
        time: "10:12 AM",
        source: "docs/privacy.md",
        owner: "Lena Ortiz",
        summary: "The first release privacy promise entered review.",
      },
      {
        id: "claim-15",
        status: "verified",
        title: "Promise updated\nData retention clarified",
        revision: "rev 3f9b1e4",
        time: "11:09 AM",
        source: "docs/privacy.md",
        owner: "Lena Ortiz",
        summary: "Retention language was narrowed to exclude message content.",
      },
      {
        id: "claim-16",
        status: "verified",
        title: "Promise unchanged\nConfirmed",
        revision: "rev 3f9b1e4",
        time: "9:41 AM",
        source: "docs/privacy.md",
        owner: "Jordan Lee",
        summary: "Privacy review confirmed the July 15 promise.",
      },
      {
        id: "claim-17",
        status: "verified",
        title: "No change",
        revision: "—",
        time: "—",
        source: "docs/privacy.md",
        owner: "Lena Ortiz",
        summary: "No claim changes were detected.",
      },
      {
        id: "privacy-conflict",
        status: "contradicted",
        title: "Contradicted\nby telemetry change",
        revision: "rev 7b2d9f0",
        time: "8:34 AM",
        source: "telemetry/events.schema.json",
        owner: "Priya Shah (Data Platform)",
        riskType: "privacy",
        confidence: 0.94,
        headline: "Telemetry change invalidated the July 16 privacy approval.",
        summary:
          "A change to event telemetry fields enables the capture of content previously outside the retention boundary.",
        excerpt: [
          '"fields": {',
          '  "message_text": {',
          '    "type": "string",',
          '    "description": "Full message content"',
          "  }",
          "}",
        ],
        contradicts:
          'Privacy approval on Jul 16, 2026 (rev 3f9b1e4): “We do not collect or store full message content.”',
        impact:
          "Enables collection of full message text, which is outside the stated retention boundary and user expectation.",
      },
    ],
  },
  {
    id: "code",
    label: "Code",
    description: "What we ship",
    events: [
      {
        id: "code-14",
        status: "verified",
        title: "Retention logic\nimplemented",
        revision: "commit 8e4f1a2",
        time: "2:15 PM",
        source: "src/retention.ts",
        owner: "Maya Patel",
        summary: "Retention logic landed with documented deletion windows.",
      },
      {
        id: "code-15",
        status: "verified",
        title: "No relevant\nchange",
        revision: "—",
        time: "—",
        source: "repository",
        owner: "Maya Patel",
        summary: "No privacy-relevant changes were detected.",
      },
      {
        id: "code-16",
        status: "verified",
        title: "No relevant\nchange",
        revision: "—",
        time: "—",
        source: "repository",
        owner: "Maya Patel",
        summary: "No privacy-relevant changes were detected.",
      },
      {
        id: "code-17",
        status: "pending",
        title: "Telemetry refactor\nmerged",
        revision: "commit d4c8b91",
        time: "4:22 PM",
        source: "src/telemetry.ts",
        owner: "Priya Shah",
        riskType: "privacy",
        confidence: 0.72,
        summary: "Telemetry refactor merged after the privacy review.",
      },
      {
        id: "code-18",
        status: "contradicted",
        title: "Telemetry schema\nchanged",
        revision: "commit b7e6c3d",
        time: "7:58 AM",
        source: "telemetry/events.schema.json",
        owner: "Priya Shah",
        riskType: "privacy",
        confidence: 0.91,
        summary: "The schema now accepts full message content.",
      },
    ],
  },
  {
    id: "tests",
    label: "Tests",
    description: "What we verify",
    events: [
      {
        id: "tests-14",
        status: "verified",
        title: "Privacy tests\npass",
        revision: "run 7f2a1c5",
        time: "3:02 PM",
        source: "CI / privacy",
        owner: "Release Bot",
        summary: "Baseline privacy tests passed.",
      },
      {
        id: "tests-15",
        status: "verified",
        title: "Retention tests\npass",
        revision: "run 9c3b7d1",
        time: "10:47 AM",
        source: "CI / retention",
        owner: "Release Bot",
        summary: "Retention window tests passed.",
      },
      {
        id: "tests-16",
        status: "verified",
        title: "E2E privacy\npass",
        revision: "run a18d9e2",
        time: "2:11 PM",
        source: "CI / end-to-end",
        owner: "Release Bot",
        summary: "The approved build passed privacy checks.",
      },
      {
        id: "tests-17",
        status: "pending",
        title: "Telemetry tests\nqueued",
        revision: "run pending",
        time: "—",
        source: "CI / telemetry",
        owner: "Release Bot",
        riskType: "privacy",
        confidence: 0.68,
        summary: "Telemetry regression tests were still queued.",
      },
      {
        id: "tests-18",
        status: "contradicted",
        title: "Privacy tests\nfail",
        revision: "run c5e8f92",
        time: "8:45 AM",
        source: "CI / privacy",
        owner: "Release Bot",
        riskType: "privacy",
        confidence: 0.96,
        summary: "The current build fails the message-content boundary test.",
      },
    ],
  },
  {
    id: "decisions",
    label: "Decisions",
    description: "Who decides",
    events: [
      {
        id: "decision-14",
        status: "verified",
        title: "PM review\nApproved",
        revision: "Alex Kim",
        time: "4:05 PM",
        source: "Launch review",
        owner: "Alex Kim",
        summary: "Product scope was approved.",
      },
      {
        id: "decision-15",
        status: "verified",
        title: "Eng review\nApproved",
        revision: "Maya Patel",
        time: "1:18 PM",
        source: "Launch review",
        owner: "Maya Patel",
        summary: "Engineering readiness was approved.",
      },
      {
        id: "decision-16",
        status: "verified",
        title: "Privacy review\nApproved",
        revision: "Jordan Lee",
        time: "3:24 PM",
        source: "Privacy review",
        owner: "Jordan Lee",
        summary: "The privacy promise matched the approved build.",
      },
      {
        id: "decision-17",
        status: "pending",
        title: "Launch readiness\nTentative GO",
        revision: "Alex Kim",
        time: "5:03 PM",
        source: "Launch review",
        owner: "Alex Kim",
        riskType: "core_workflow",
        confidence: 0.73,
        summary: "Launch remained tentative until the queued telemetry tests completed.",
      },
      {
        id: "decision-18",
        status: "contradicted",
        title: "Launch decision\nBLOCKED",
        revision: "Jordan Lee",
        time: "9:12 AM",
        source: "Launch review",
        owner: "Jordan Lee",
        riskType: "privacy",
        confidence: 0.98,
        summary: "The prior approval is blocked by current evidence.",
      },
    ],
  },
];

export const defaultFindings = lanes
  .flatMap((lane) => lane.events)
  .filter((event) => event.status === "pending" || event.status === "contradicted")
  .map((event) => ({
    id: event.id,
    status: event.status,
    confidence: event.confidence,
    riskType: event.riskType,
  }));

export const analysisPayload = {
  claim: {
    id: "privacy-promise-3f9b1e4",
    text: "We do not collect or store full message content.",
  },
  decision: {
    id: "privacy-approval-jul-16",
    summary: "Privacy review approved the launch because message content was excluded.",
    approvedAt: "2026-07-16T15:24:00Z",
  },
  sources: [
    {
      id: "privacy-promise-3f9b1e4",
      kind: "claim",
      title: "Privacy promise",
      revision: "3f9b1e4",
      updatedAt: "2026-07-16T09:41:00Z",
      content: "We do not collect or store full message content.",
    },
    {
      id: "telemetry-schema-b7e6c3d",
      kind: "code",
      title: "Telemetry event schema",
      revision: "b7e6c3d",
      updatedAt: "2026-07-18T07:58:00Z",
      content:
        'A message_text string field was added with the description "Full message content".',
    },
    {
      id: "privacy-ci-c5e8f92",
      kind: "test",
      title: "Privacy boundary test",
      revision: "c5e8f92",
      updatedAt: "2026-07-18T08:45:00Z",
      content:
        "FAILED: telemetry payload includes message_text; expected content boundary exclusion.",
    },
  ],
};
