export const release = {
  id: "nova-2.4",
  name: "Nova 2.4 Launch",
  date: "July 21, 2026",
  dateISO: "2026-07-21T15:00:00Z",
  snapshotDate: "July 18, 2026",
  snapshotISO: "2026-07-18T09:12:00Z",
  evidenceHead: "nova-2.4@7b2d9f0",
  datasetLabel: "Synthetic demo snapshot",
  reviewer: "Jordan Lee",
  days: [
    { id: "jul-14", weekday: "Tue", date: "14" },
    { id: "jul-15", weekday: "Wed", date: "15" },
    { id: "jul-16", weekday: "Thu", date: "16" },
    { id: "jul-17", weekday: "Fri", date: "17" },
    { id: "jul-18", weekday: "Sat", date: "18", current: true },
  ],
};

export const claims = [
  {
    id: "privacy-message-content",
    title: "Message-content privacy boundary",
    text: "We do not collect or store full message content.",
    riskType: "privacy",
    material: true,
    currentRevision: "3f9b1e4",
    updatedAt: "2026-07-16T09:41:00Z",
    requiredEvidenceKinds: ["claim", "code", "test"],
  },
];

export const evidenceSources = [
  {
    id: "privacy-promise-3f9b1e4",
    claimId: "privacy-message-content",
    kind: "claim",
    title: "Privacy promise",
    path: "docs/privacy.md",
    revision: "3f9b1e4",
    updatedAt: "2026-07-16T09:41:00Z",
    relation: "supports",
    confidence: 1,
    content: "We do not collect or store full message content.",
  },
  {
    id: "retention-code-8e4f1a2",
    claimId: "privacy-message-content",
    kind: "code",
    title: "Retention implementation",
    path: "src/retention.ts",
    revision: "8e4f1a2",
    updatedAt: "2026-07-14T14:15:00Z",
    relation: "supports",
    confidence: 0.91,
    content: "Message content is excluded from retained telemetry records.",
  },
  {
    id: "privacy-e2e-a18d9e2",
    claimId: "privacy-message-content",
    kind: "test",
    title: "Approved-build privacy test",
    path: "CI / end-to-end",
    revision: "a18d9e2",
    updatedAt: "2026-07-16T14:11:00Z",
    relation: "supports",
    confidence: 0.96,
    content: "PASS: approved build excludes message content from telemetry.",
  },
  {
    id: "telemetry-schema-d4c8b91",
    claimId: "privacy-message-content",
    kind: "code",
    title: "Telemetry event schema before refactor",
    path: "telemetry/events.schema.json",
    revision: "d4c8b91",
    updatedAt: "2026-07-17T16:22:00Z",
    relation: "supports",
    confidence: 0.9,
    content:
      '"fields": { "event_name": { "type": "string" }, "message_length": { "type": "integer" } }',
  },
  {
    id: "telemetry-schema-b7e6c3d",
    claimId: "privacy-message-content",
    kind: "code",
    title: "Telemetry event schema after refactor",
    path: "telemetry/events.schema.json",
    revision: "b7e6c3d",
    updatedAt: "2026-07-18T07:58:00Z",
    relation: "contradicts",
    confidence: 0.94,
    content:
      '"fields": { "message_text": { "type": "string", "description": "Full message content" } }',
  },
  {
    id: "privacy-ci-c5e8f92",
    claimId: "privacy-message-content",
    kind: "test",
    title: "Current privacy boundary test",
    path: "CI / privacy",
    revision: "c5e8f92",
    updatedAt: "2026-07-18T08:45:00Z",
    relation: "contradicts",
    confidence: 0.96,
    content:
      "FAILED: telemetry payload includes message_text; expected content boundary exclusion.",
  },
];

export const initialDecisions = [
  {
    id: "pm-approval-jul-14",
    type: "approval",
    claimId: null,
    issueId: null,
    status: "approved",
    actor: "Alex Kim",
    reason: "Product scope is ready for release review.",
    createdAt: "2026-07-14T16:05:00Z",
    evidenceHead: "nova-2.4@8e4f1a2",
    basedOnEvidenceIds: ["retention-code-8e4f1a2"],
  },
  {
    id: "engineering-approval-jul-15",
    type: "approval",
    claimId: null,
    issueId: null,
    status: "approved",
    actor: "Maya Patel",
    reason: "Engineering readiness checks passed for the reviewed revision.",
    createdAt: "2026-07-15T13:18:00Z",
    evidenceHead: "nova-2.4@9c3b7d1",
    basedOnEvidenceIds: ["retention-code-8e4f1a2"],
  },
  {
    id: "privacy-approval-jul-16",
    type: "approval",
    claimId: "privacy-message-content",
    issueId: null,
    status: "approved",
    actor: "Jordan Lee",
    reason: "The reviewed build excludes full message content from telemetry.",
    createdAt: "2026-07-16T15:24:00Z",
    evidenceHead: "nova-2.4@a18d9e2",
    basedOnEvidenceIds: [
      "privacy-promise-3f9b1e4",
      "retention-code-8e4f1a2",
      "privacy-e2e-a18d9e2",
    ],
  },
  {
    id: "launch-readiness-jul-17",
    type: "approval",
    claimId: null,
    issueId: null,
    status: "pending",
    actor: "Alex Kim",
    reason: "Awaiting the current telemetry test run.",
    createdAt: "2026-07-17T17:03:00Z",
    evidenceHead: "nova-2.4@d4c8b91",
    basedOnEvidenceIds: ["telemetry-schema-d4c8b91"],
  },
];

export const lanes = [
  {
    id: "claim",
    label: "Claim",
    description: "What we promise",
    events: [
      {
        id: "claim-14",
        claimId: "privacy-message-content",
        evidenceId: "privacy-promise-3f9b1e4",
        status: "verified",
        title: "Privacy promise v1.0 published",
        revision: "rev 1a7c3d2",
        time: "10:12 AM",
        timestamp: "2026-07-14T10:12:00Z",
        source: "docs/privacy.md",
        owner: "Lena Ortiz",
        confidence: 1,
        summary: "The first release privacy promise entered review.",
      },
      {
        id: "claim-15",
        claimId: "privacy-message-content",
        evidenceId: "privacy-promise-3f9b1e4",
        status: "verified",
        title: "Promise updated\nData retention clarified",
        revision: "rev 3f9b1e4",
        time: "11:09 AM",
        timestamp: "2026-07-15T11:09:00Z",
        source: "docs/privacy.md",
        owner: "Lena Ortiz",
        confidence: 1,
        summary: "Retention language was narrowed to exclude message content.",
      },
      {
        id: "claim-16",
        claimId: "privacy-message-content",
        evidenceId: "privacy-promise-3f9b1e4",
        status: "verified",
        title: "Promise unchanged\nConfirmed",
        revision: "rev 3f9b1e4",
        time: "9:41 AM",
        timestamp: "2026-07-16T09:41:00Z",
        source: "docs/privacy.md",
        owner: "Jordan Lee",
        confidence: 1,
        summary: "Privacy review confirmed the July 15 promise.",
      },
      {
        id: "claim-17",
        claimId: "privacy-message-content",
        status: "unproven",
        title: "No new claim revision",
        revision: "—",
        time: "—",
        timestamp: "2026-07-17T23:59:00Z",
        source: "docs/privacy.md",
        owner: "Lena Ortiz",
        confidence: null,
        summary: "No new claim revision was recorded for this date.",
      },
      {
        id: "privacy-conflict",
        claimId: "privacy-message-content",
        issueId: "privacy-message-content:current-conflict",
        evidenceId: "telemetry-schema-b7e6c3d",
        status: "contradicted",
        title: "Contradicted\nby telemetry change",
        revision: "rev b7e6c3d",
        time: "8:34 AM",
        timestamp: "2026-07-18T08:34:00Z",
        source: "telemetry/events.schema.json",
        owner: "Priya Shah (Data Platform)",
        confidence: 0.94,
        headline: "Telemetry change invalidated the July 16 privacy approval.",
        summary:
          "Newer code and test evidence contradict the current message-content privacy claim.",
        excerpt: [
          '"fields": {',
          '  "message_text": {',
          '    "type": "string",',
          '    "description": "Full message content"',
          "  }",
          "}",
        ],
        previousRevision: "d4c8b91",
        previousExcerpt: [
          '"fields": {',
          '  "event_name": { "type": "string" },',
          '  "message_length": { "type": "integer" }',
          "}",
        ],
        contradicts:
          "Privacy approval on Jul 16, 2026 (rev 3f9b1e4): “We do not collect or store full message content.”",
        impact:
          "Full message text is now allowed by the current schema and detected by the current privacy test.",
      },
    ],
  },
  {
    id: "code",
    label: "Code",
    description: "What we ship",
    events: [
      {
        id: "code-14",
        claimId: "privacy-message-content",
        evidenceId: "retention-code-8e4f1a2",
        status: "verified",
        title: "Retention logic\nimplemented",
        revision: "commit 8e4f1a2",
        time: "2:15 PM",
        timestamp: "2026-07-14T14:15:00Z",
        source: "src/retention.ts",
        owner: "Maya Patel",
        confidence: 0.91,
        summary: "Retention logic excludes message content from stored telemetry.",
      },
      {
        id: "code-15",
        claimId: "privacy-message-content",
        status: "unproven",
        title: "No relevant\nchange",
        revision: "—",
        time: "—",
        timestamp: "2026-07-15T23:59:00Z",
        source: "repository",
        owner: "Maya Patel",
        confidence: null,
        summary: "No privacy-relevant code revision was recorded for this date.",
      },
      {
        id: "code-16",
        claimId: "privacy-message-content",
        status: "unproven",
        title: "No relevant\nchange",
        revision: "—",
        time: "—",
        timestamp: "2026-07-16T23:59:00Z",
        source: "repository",
        owner: "Maya Patel",
        confidence: null,
        summary: "No privacy-relevant code revision was recorded for this date.",
      },
      {
        id: "code-17",
        claimId: "privacy-message-content",
        evidenceId: "telemetry-schema-d4c8b91",
        status: "pending",
        title: "Telemetry refactor\nmerged",
        revision: "commit d4c8b91",
        time: "4:22 PM",
        timestamp: "2026-07-17T16:22:00Z",
        source: "telemetry/events.schema.json",
        owner: "Priya Shah",
        confidence: 0.9,
        summary: "The refactor landed after privacy approval and awaited the current test run.",
      },
      {
        id: "code-18",
        claimId: "privacy-message-content",
        issueId: "privacy-message-content:current-conflict",
        evidenceId: "telemetry-schema-b7e6c3d",
        status: "contradicted",
        title: "Telemetry schema\nchanged",
        revision: "commit b7e6c3d",
        time: "7:58 AM",
        timestamp: "2026-07-18T07:58:00Z",
        source: "telemetry/events.schema.json",
        owner: "Priya Shah",
        confidence: 0.94,
        summary: "The current schema allows full message content.",
      },
    ],
  },
  {
    id: "tests",
    label: "Tests",
    description: "What we verify",
    events: [
      {
        id: "tests-14",
        claimId: "privacy-message-content",
        status: "verified",
        title: "Privacy tests\npass",
        revision: "run 7f2a1c5",
        time: "3:02 PM",
        timestamp: "2026-07-14T15:02:00Z",
        source: "CI / privacy",
        owner: "Release Bot",
        confidence: 0.96,
        summary: "Baseline privacy tests passed.",
      },
      {
        id: "tests-15",
        claimId: "privacy-message-content",
        status: "verified",
        title: "Retention tests\npass",
        revision: "run 9c3b7d1",
        time: "10:47 AM",
        timestamp: "2026-07-15T10:47:00Z",
        source: "CI / retention",
        owner: "Release Bot",
        confidence: 0.95,
        summary: "Retention-window tests passed.",
      },
      {
        id: "tests-16",
        claimId: "privacy-message-content",
        evidenceId: "privacy-e2e-a18d9e2",
        status: "verified",
        title: "E2E privacy\npass",
        revision: "run a18d9e2",
        time: "2:11 PM",
        timestamp: "2026-07-16T14:11:00Z",
        source: "CI / end-to-end",
        owner: "Release Bot",
        confidence: 0.96,
        summary: "The approved build passed the privacy boundary check.",
      },
      {
        id: "tests-17",
        claimId: "privacy-message-content",
        status: "pending",
        title: "Telemetry tests\nqueued",
        revision: "run pending",
        time: "—",
        timestamp: "2026-07-17T17:05:00Z",
        source: "CI / telemetry",
        owner: "Release Bot",
        confidence: null,
        summary: "The current telemetry regression tests had not completed.",
      },
      {
        id: "tests-18",
        claimId: "privacy-message-content",
        issueId: "privacy-message-content:current-conflict",
        evidenceId: "privacy-ci-c5e8f92",
        status: "contradicted",
        title: "Privacy tests\nfail",
        revision: "run c5e8f92",
        time: "8:45 AM",
        timestamp: "2026-07-18T08:45:00Z",
        source: "CI / privacy",
        owner: "Release Bot",
        confidence: 0.96,
        summary: "The current build fails the message-content boundary test.",
      },
    ],
  },
  {
    id: "decisions",
    label: "Decisions",
    description: "Who decides",
    events: [
      {
        id: "decision-14",
        decisionId: "pm-approval-jul-14",
        status: "verified",
        title: "PM review\nApproved",
        revision: "Alex Kim",
        time: "4:05 PM",
        timestamp: "2026-07-14T16:05:00Z",
        source: "Launch review",
        owner: "Alex Kim",
        confidence: null,
        summary: "Product scope was approved against the recorded evidence head.",
      },
      {
        id: "decision-15",
        decisionId: "engineering-approval-jul-15",
        status: "verified",
        title: "Eng review\nApproved",
        revision: "Maya Patel",
        time: "1:18 PM",
        timestamp: "2026-07-15T13:18:00Z",
        source: "Launch review",
        owner: "Maya Patel",
        confidence: null,
        summary: "Engineering readiness was approved against the reviewed revision.",
      },
      {
        id: "decision-16",
        claimId: "privacy-message-content",
        decisionId: "privacy-approval-jul-16",
        status: "verified",
        title: "Privacy review\nApproved",
        revision: "Jordan Lee",
        time: "3:24 PM",
        timestamp: "2026-07-16T15:24:00Z",
        source: "Privacy review",
        owner: "Jordan Lee",
        confidence: null,
        summary: "The privacy promise matched the evidence head reviewed on July 16.",
      },
      {
        id: "decision-17",
        decisionId: "launch-readiness-jul-17",
        status: "pending",
        title: "Launch readiness\nAwaiting tests",
        revision: "Alex Kim",
        time: "5:03 PM",
        timestamp: "2026-07-17T17:03:00Z",
        source: "Launch review",
        owner: "Alex Kim",
        confidence: null,
        summary: "The decision remains pending until current telemetry tests complete.",
      },
      {
        id: "decision-18",
        claimId: "privacy-message-content",
        issueId: "privacy-message-content:current-conflict",
        status: "contradicted",
        title: "Gate reevaluated\nNO-GO",
        revision: "policy engine",
        time: "9:12 AM",
        timestamp: "2026-07-18T09:12:00Z",
        source: "Deterministic gate",
        owner: "Release Truth",
        confidence: null,
        summary: "The policy engine blocked launch from one deduplicated privacy issue.",
      },
    ],
  },
];
